# Generated by Django 5.1.7 on 2026-02-15 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetupSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("meeting_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetup_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetupResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=200)),
                ("station_lat", models.FloatField()),
                ("station_lon", models.FloatField()),
                ("score_fairness", models.FloatField(null=True)),
                ("score_efficiency", models.FloatField(null=True)),
                ("score_quick_arrival", models.FloatField(null=True)),
                ("score_easy_home", models.FloatField(null=True)),
                ("journey_details_json", models.TextField(default="{}")),
                ("google_maps_url", models.URLField(max_length=500)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="meetup.meetupsession",
                    ),
                ),
            ],
            options={
                "ordering": ["score_fairness"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("origin_label", models.CharField(max_length=255)),
                ("origin_lat", models.FloatField()),
                ("origin_lon", models.FloatField()),
                ("home_label", models.CharField(max_length=255)),
                ("home_lat", models.FloatField()),
                ("home_lon", models.FloatField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="meetup.meetupsession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "people",
            },
        ),
    ]
