# Generated by Django 5.1.7 on 2025-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tool', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated from name)', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this tool does')),
                ('html_content', models.TextField(help_text='Paste the complete HTML artifact code here')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tool is publicly accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_exported', models.DateTimeField(blank=True, help_text='When this tool was last exported to git', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this tool has been accessed')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['-created_at'],
            },
        ),
    ]
